### PR TITLE
40 add unit tests to existing functions

### PR DESCRIPTION
**Pull request by rqding**
1. Fix the project relative path issue which causing the web page format incorrectly (please see screenshot below)
2. Add unit tests to the project model, organization model, and organization type model.
3. Update the documentation to use docker compose command
Screenshot 2023-11-01 at 16 24 05
Screenshot 2023-11-01 at 16 26 13

### CODE REVIEW

**Comment by signekb** [comment]
@rqding. I find this a bit difficult to review since I haven't been introduced to this codebase yet (as you suggested last week that I should). I don't have time for an introduction before going to Copenhagen next week, but we can setup a meeting in W46?

**Comment by lwjohnst86** [comment]
I also had a hard time looking this over and understanding what was going on. I had to actually make some small modifications in order for it to work and show on my localhost. @rqding next PR, please make them more focused and smaller. It doesn't help us work effectively if it takes a lot of effort and time to review PRs.

@signekb since this is drifting outside the scope of the focus period, hold off on reviewing it until we can dedicate full time to diving into the code and building pieces up, so we can more effectively review and understand PRs.

**Comment by signekb** [comment]
@lwjohnst86 good point. we'll wait :)

**Comment by rqding** [comment]
@lwjohnst86 As I explained in the meeting, there are three parts of this  PR, 1. fixing the existing relative path issue which already exists in the main branch. 2. Add basic unit tests for the two data models. 3. Make sure the unit tests running for the integration script. I am not sure how to make a more focused and smaller PR. Could you help me with that? Could you use this PR as an example that provides some specific suggestions on how should I make this PR smaller?

**Comment by lwjohnst86** [comment]
@rqding you describe quite well how to make it smaller, by having three PRs for each of the "parts" you mention.

**Pull request closed without merging**
